### PR TITLE
SEPARATOR token_type 

### PR DESCRIPTION
**Pull request by spralja**
I have added the separator token_type, read commit motivation for further information

### CODE REVIEW

**Comment by miningape** [comment]
What information do we lose by ignoring whitespace?

**Comment by miningape** [comment]
@spralja why would it be useful? Can you give an example?

cus the only time we are talking about problems with whitespace as far as I can think is in the tokeniser (since whitespace doesn't have a role in parsing) and since the tokeniser has the line+character it can (and I think already does) report errors and tell where a token is

**Comment by miningape** [comment]
Just an FYI you can name branches like `spralja/SEPERATOR` for example, which is nice because it puts a branch called `SEPERATOR` in a folder called `spralja` which can be nice, since then all ur branches are in one neat folder (ofc this is just a bit of silly extra info)

**Comment by spralja** [comment]
> Just an FYI you can name branches like `spralja/SEPERATOR` for example, which is nice because it puts a branch called `SEPERATOR` in a folder called `spralja` which can be nice, since then all ur branches are in one neat folder (on github, idk about other things) (ofc this is just a bit of silly extra info, I'm not asking u to do anything :D )

@miningape I didn't know that sounds useful

**Pull request closed without merging**
