### PR TITLE
Feat: REPL

### PR DESCRIPTION
**Pull request by miningape**
Allows script to run and either read a file or open a repl (depending on if filename is given in args), at the moment instead of running anything it just prints

### CODE REVIEW

**Review by spralja — COMMENTED** [review]
I think that's a good way to do stuff, but I think there is a way to do this inside the module.
like the way you can run venv or pip with:
`py - m pip`
`py -m venv`

I think that's a better way to do it

**Comment by spralja** [comment]
And then you can alias it or something

**Comment by miningape** [comment]
@spralja the point of this PR isn't to make an executable, its to give an interface that we can work with easily. That comes much later and for the most part is just automated by build tools (That means we can take this code and turn it directly into an app like `pip` or `venv` without changing anything)

**Comment by miningape** [comment]
Closed since it was merged by merging the Tokeniser PR

**Pull request closed without merging**
