### PR TITLE
Implementation of Errors, and error handling

### PR DESCRIPTION
**Pull request by spralja**
Includes branches `expressions` and `__main__`.

### CODE REVIEW

**Comment by miningape** [comment]
Why pull expressions PR? It seems like u aren't using any of the code there, making this just a PR that merges 2 others

**Comment by spralja** [comment]
> Why pull expressions PR? It seems like u aren't using any of the code there, making this just a PR that merges 2 others

@miningape I changed your `raise` to raise our exceptions instead of python exceptions to differentiation errors.

**Comment by miningape** [comment]
> > Why pull expressions PR? It seems like u aren't using any of the code there, making this just a PR that merges 2 others
> 
> @miningape I changed your `raise` to raise our exceptions instead of python exceptions to differentiation errors.

Don't do that, this PR is focussed on bringing error handling into main, as such it should be separate from the expression pr. This also means that once this PR is merged into main (or before) the expression PR should implement those changes. 

Doing it this way will let you merge this pr sooner, and it means it relies on less being merged into main before this one (aka less of a clusterfuck). It also means that each PR is more focussed, ideally the expression PR deals only with expressions, and the error PR deals only with errors which means its easier to reason with when reading the PR (for this reason, and the fact you merged it in here already. I think your error interface PR and this one should be merged and one of them closed). 

Ofc there is a balancing act here because you dont want PRs to become too massive (we would fix this problem by running sprints properly but i dont think its worth it since for the most part our PRs are small <1000 lines)

**Comment by spralja** [comment]
@miningape I suppose this pull request is more concerned with getting some feedback of the implementation?

I was thinking that If we wish to be able to print stack trace and where the error happened, we must either append a traceback, or somehow guess it based on the python traceback

**Pull request closed without merging**
